# Docker Compose file that creates the development environemnt
version: "3.8"

services:
  api_users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    entrypoint: ["bash", "/usr/src/app/entrypoint.sh"]
    volumes:
      - "./services/users:/usr/src/app"
      - "./services/users/src/media:/usr/src/datasets"
    ports:
      - 5004:5000
    env_file:
      - ./.env.dev
    depends_on:
      - api_users_db

  api_users_db:
    build:
      context: ./services/users/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    stdin_open: true
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - "./services/client:/app"
      - "/app/node_modules"
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - api_users
