version: "3.8"

services:
  api_users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    entrypoint: ["bash", "/usr/src/app/entrypoint.sh"]
    volumes:
      - "./services/users:/usr/src/app"
    ports:
      - 5004:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_USERS_URL=postgresql://postgres:postgres@api_users_db:5432/api_users_dev
      - DATABASE_TEST_USERS_URL=postgresql://postgres:postgres@api_users_db:5432/api_users_test
    depends_on:
      - api_users_db

  api_users_db:
    build:
      context: ./services/users/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api_climate:
    build:
      context: ./services/climate
      dockerfile: Dockerfile
    entrypoint: ["bash", "/usr/src/app/entrypoint.sh"]
    volumes:
      - ./services/climate:/usr/src/app
    ports:
      - 5005:5000
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
    depends_on:
      - api_climate_db

  api_climate_db:
    build:
      context: ./services/climate/db
      dockerfile: Dockerfile
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb

  client:
    stdin_open: true
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - "./services/client:/app"
      - "/app/node_modules"
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
      - REACT_APP_CLIMATE_SERVICE_URL=${REACT_APP_CLIMATE_SERVICE_URL}
    depends_on:
      - api_users
      - api_climate
