version: '3.8'

services:

  api_users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - ./services/users:/usr/src/app
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_USERS_URL=postgresql://postgres:postgres@api-db:5432/api_users_dev
      - DATABASE_TEST_USERS_URL=postgresql://postgres:postgres@api-db:5432/api_users_test
    depends_on:
      - api_users_db


  api_users_db:
    build:
      context: ./services/users/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
