name: Continous Integration with the building Docker images
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create env file
        run: |
          cat << EOF > .env.dev
          FLASK_ENV=development
          echo FLASK_SETTINGS > .env.dev
          echo DATABASE_USERS_URL=postgresql://postgres:postgres@api_users_db:5432/api_users_dev
          echo DATABASE_TEST_USERS_URL=postgresql://postgres:postgres@api_users_db:5432/api_users_test
          echo APP_FOLDER=/usr/src/app
          EOF
      - name: Build the services using docker-compose
        run: docker-compose up -d --build
      - name: Test
        run: docker-compose exec -T api_users python -m pytest "src/tests" -p no:warnings
      - name: Bring down the container
        run: docker-compose down -v
